### ISSUE TITLE
Please update to phosh 0.34.0

### ISSUE THREAD

**Issue by agx** [droidian/phosh#8]
From a quick look it seems droidian is using older phoc. That won't work well with phosh >= 0.34.0 as the kwin-idle protocol got dropped. If you can't use newer phoc due to your wlroots dependency atm reverting those bits works. Reverting 

95fdfb86556b2fafde0ec92dbf1932de254e91cb.
3c10c1227572d02010663b5e4d7fa3bef3af231f.
dc99416ecedb99bcafc7f0f36f7b184ea7cad70c.
72caeb045804ac82b5c121bd363c12af9fa29659.

allows you to use older phoc for the moment. (Feel free to close the issue, just wanted to leave a note as I did the same for Byzantium)

**Comment by g7** [comment]
Hi, these have been reverted on https://github.com/droidian/phosh/commits/feature/trixie/upgrade-0.34.0/ and will soon reach everyone.

By the way, thank you very much for reaching out and even detailing what needs to be reverted. It's really appreciated! :)
